### ISSUE TITLE
HOME mobile

### ISSUE THREAD

**Issue by cchiara** [adraxyz/help-projects#10]
SECTION 0
- [x] detach logo from left margin - margin left = margin top
- [x] remove social icons
- [x] put the "action button" lower
- [x] add space between blue box and blue text 
- [x] raise all the section 0 to avoid being hidden beneath the browser bottom bar (see image attached) ![IMG_F4BF2F5C84F8-1](https://user-images.githubusercontent.com/48411554/80796899-b2dbd100-8ba0-11ea-8c99-689168177af6.jpeg)
- [x] add image switch before-after

SECTION 1 
- [x]  reduce text box width and move image accordingly 
![IMG_83AAC4E52D74-1](https://user-images.githubusercontent.com/48411554/80797674-bd976580-8ba2-11ea-86b4-08202c58732c.jpeg)
- [x]  shrink donate button to circle after section 0 NOT AFTER SECTION 1
- [x]  increase image 3 height of section 1

SECTION 3 
- [x]  reduce text column width 
- [x]  change text style: 
font-family Crossten Light 
line-height 2 
line-spacing 0.09 rem 
- [x]  center to page "find out more" button

SECTION 4 TEXT 
- [x]  send author name on a new line
change font-size = font-size text above

**Comment by cchiara** [comment]
2. togliere loghi social

**Comment by cchiara** [comment]
3. lower the "fai partire il cantiere" button 
4. add space between the blue box and the blue text

**Comment by adraxyz** [comment]
About the following points:
- put the "action button" lower
- add space between blue box and blue text
- raise all the section 0 to avoid being hidden beneath the browser bottom bar (see image attached)

The home page section 0 on Android smartphone looks like this:
![screenshot.jpg](https://images.zenhubusercontent.com/5eabf9800e94d543ced62bc5/14c047d0-a1a7-4f0c-a2bc-bd210ac743e7)

The 3 points above involve a significant reduction of the fonts sizes, button size and so on --> it involves #9

**Comment by adraxyz** [comment]
About this point:
" shrink donate button to circle after section 0 NOT AFTER SECTION 1"
it seems to be already as wanted on android devices. @cchiara is it different on iphone?

**Comment by adraxyz** [comment]
@cchiara what does "increase image 3 height of section 1" means? All the section 1 images have the same height, do you want to introduce an exception for the third image? It could seem lower because of the white space on top but I think the right way to reduce this visual effect is to make the image bigger inside the same bounding box. Are you agree?

**Comment by adraxyz** [comment]
About the last point of the issue ("send author name on a new line and change font-size = font-size text above") --> it will be managed through the html inside the text input (from the backend admin)
