### ISSUE TITLE
Contact us - mobile

### ISSUE THREAD

**Issue by cchiara** [adraxyz/help-projects#12]
- [ ] reduce column width accordingly to home changes 
- [ ] remove donate button 
- [x] correct sentence " accetto i termini dle servizio" typo "dle" 
- [ ] something wrong with privacy policy text 
![IMG_3774A9CC898C-1](https://user-images.githubusercontent.com/48411554/80798417-9f326980-8ba4-11ea-8e14-3f493c9f47fa.jpeg)
- [ ] remove letter gif

**Comment by adraxyz** [comment]
On some devices the contact form does not work fine: once a field has been populated, the typed value disappear switching to another field (TODO. provide visual example)

**Comment by adraxyz** [comment]
@cchiara why "remove donate button" ???
