### ISSUE TITLE
Who and What - mobile 

### ISSUE THREAD

**Issue by cchiara** [adraxyz/help-projects#18]
- [x] in function section - switch image and text order (put image first) 
- [x]  in function section - increase image sizes to match the ones in "get involved"
![IMG_3BAD7056EE45-1](https://user-images.githubusercontent.com/48411554/80800413-ae67e600-8ba9-11ea-8a8d-ddfda03761f4.jpeg)
- [x] change text style, se issue #15 
- [x]  section "where we are" raise the image above to align with text (if possible)
![IMG_B1F66ADECAA6-1.jpeg](https://images.zenhubusercontent.com/5eabfc65896abe4b7cf6d5a3/5cc253ba-11c5-4584-bfb0-b0a9f04fedda)
- [x] section "download" - center button "download" to box
- [x] section download - realign black text with orange text 
![IMG_E0BBC0D8BC06-1.jpeg](https://images.zenhubusercontent.com/5eabfc65896abe4b7cf6d5a3/ec903b8b-0d8f-4d62-bd50-b182e2daefaa)

**Comment by adraxyz** [comment]
@cchiara "section "where we are" raise the image above to align with text (if possible)" --> not possible at the moment, it will be investigated later

**Comment by adraxyz** [comment]
"where we are" section graphic glitch in desktop mode also --> we should fix it
