### ISSUE TITLE
DONATE 

### ISSUE THREAD

**Issue by cchiara** [adraxyz/help-projects#23]
- [x] switch pigeon image 
- [x] reduce box height of n.1 to stop right after the paypal button
![Screenshot 2020-05-01 at 14.40.06.png](https://images.zenhubusercontent.com/5eabfc65896abe4b7cf6d5a3/99745f16-edc3-4777-9fa1-61aa16fd5578) 
- [x] end image before the end of the boxes 
- [x] center the button "learn more" on the 5x1000 box
- [x] add facebook payments next to box n.6 
![Screenshot 2020-05-01 at 14.44.17.jpg](https://images.zenhubusercontent.com/5eabfc65896abe4b7cf6d5a3/1aaf1ea8-4ca7-400f-b9b4-e9f5d8393233)

**Comment by adraxyz** [comment]
@cchiara the last image you pasted is not rendered

**Comment by adraxyz** [comment]
The section has been refactored but the issue points have been considered
