### ISSUE TITLE
Font adjustment

### ISSUE THREAD

**Issue by adraxyz** [adraxyz/help-projects#4]
Texts adjustments.

title:
- font-family: Crossten Bold
- font-size: 30px
- line-spacing: 0.09 rem
- line-height: ??? (default 100%)

subtitle:
- font-family: Crossten Bold
- font-size: 20px
- line-spacing: 0.09 rem
- line-height: 100%

content:
- font-family: Crossten Light
- font-size: 20px
- line-spacing: 0.09 rem
- line-height: 2

Button:
same as 
![immagine](https://user-images.githubusercontent.com/45832890/80739994-b2e3be80-8b17-11ea-9f9c-3074cbf5963d.png)

**Comment by cchiara** [comment]
@adraxyz 
- [ ] can we try reducing these font size? make them the same as the home numbers? (7.000.000, 140.000...) 
- [ ] can we try reducing the font size of the text below to match the title style? (20px, bold, 2vm...) 
 ![Screenshot 2020-05-02 at 09.43.39.jpg](https://images.zenhubusercontent.com/5eabfc65896abe4b7cf6d5a3/8342965f-9c46-4753-ab52-7028a588452e)
